// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script} from "forge-std/Script.sol";
import {console2} from "forge-std/console2.sol";
import {AnonsDescriptor} from "../src/AnonsDescriptor.sol";

/// @title UploadTraitNames
/// @notice Script to upload human-readable trait names to the descriptor
/// @dev Run after traits are uploaded to set display names for metadata
contract UploadTraitNames is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address descriptorAddress = vm.envAddress("DESCRIPTOR_ADDRESS");

        AnonsDescriptor descriptor = AnonsDescriptor(descriptorAddress);

        vm.startBroadcast(deployerPrivateKey);

        console2.log("=== Uploading Trait Names ===");
        console2.log("Descriptor:", descriptorAddress);
        console2.log("");

        // Background names (dawn + dusk)
        string[] memory backgroundNames = new string[](4);
        backgroundNames[0] = "Dawn Sky";
        backgroundNames[1] = "Dawn Clouds";
        backgroundNames[2] = "Dusk Sky";
        backgroundNames[3] = "Dusk Clouds";
        
        console2.log("Setting background names...");
        descriptor.setBackgroundNames(backgroundNames);
        console2.log("  >> %d background names uploaded", backgroundNames.length);

        // Head names
        string[] memory headNames = getHeadNames();
        console2.log("Setting head names...");
        descriptor.setHeadNames(headNames);
        console2.log("  >> %d head names uploaded", headNames.length);

        // Body names
        string[] memory bodyNames = getBodyNames();
        console2.log("Setting body names...");
        descriptor.setBodyNames(bodyNames);
        console2.log("  >> %d body names uploaded", bodyNames.length);

        // Specs names
        string[] memory specsNames = getSpecsNames();
        console2.log("Setting specs names...");
        descriptor.setSpecsNames(specsNames);
        console2.log("  >> %d specs names uploaded", specsNames.length);

        // Antenna names
        string[] memory antennaNames = getAntennaNames();
        console2.log("Setting antenna names...");
        descriptor.setAntennaNames(antennaNames);
        console2.log("  >> %d antenna names uploaded", antennaNames.length);

        // Accessory names
        string[] memory accessoryNames = getAccessoryNames();
        console2.log("Setting accessory names...");
        descriptor.setAccessoryNames(accessoryNames);
        console2.log("  >> %d accessory names uploaded", accessoryNames.length);

        vm.stopBroadcast();

        console2.log("");
        console2.log("=== All trait names uploaded successfully ===");
    }

    // Trait name helper functions - generated from pipeline output

    function getHeadNames() internal pure returns (string[] memory) {
        string[] memory names = new string[](189);
        names[0] = "Abstract";
        names[1] = "Air Conditioner";
        names[2] = "Alarm Clock";
        names[3] = "ATM";
        names[4] = "Bag";
        names[5] = "Bank";
        names[6] = "Barcode";
        names[7] = "Baseball Gameball";
        names[8] = "Basketball";
        names[9] = "Battery";
        names[10] = "Bell";
        names[11] = "Blackhole";
        names[12] = "Blender";
        names[13] = "Bomb";
        names[14] = "Boombox";
        names[15] = "Box";
        names[16] = "Boxingglove";
        names[17] = "Broken LCD";
        names[18] = "Bubble Speech";
        names[19] = "Calculator";
        names[20] = "Calendar";
        names[21] = "Camcorder";
        names[22] = "Car";
        names[23] = "Cash Register";
        names[24] = "Cassettetape";
        names[25] = "Cctv";
        names[26] = "Cd";
        names[27] = "Chain";
        names[28] = "Chainsaw";
        names[29] = "Chart Bars";
        names[30] = "Chipboard";
        names[31] = "Circuit Breaker";
        names[32] = "Clapperboard";
        names[33] = "Cloud";
        names[34] = "Clutch";
        names[35] = "Coffee Maker";
        names[36] = "Compass";
        names[37] = "Cone";
        names[38] = "Console Handheld";
        names[39] = "Cordlessphone";
        names[40] = "Couch";
        names[41] = "CRT BSOD";
        names[42] = "CRT Static";
        names[43] = "Crystalball";
        names[44] = "Curling Stone";
        names[45] = "Dashcam";
        names[46] = "Diamond Blue";
        names[47] = "Diamond Red";
        names[48] = "Dictionary";
        names[49] = "Disco Ball";
        names[50] = "Drill";
        names[51] = "E Ink";
        names[52] = "Earth";
        names[53] = "Faberge";
        names[54] = "Factory Dark";
        names[55] = "Fan";
        names[56] = "Fax Machine";
        names[57] = "Fence";
        names[58] = "Film 35mm";
        names[59] = "Film Strip";
        names[60] = "Fire Extinguisher";
        names[61] = "Firehydrant";
        names[62] = "Flip Phone";
        names[63] = "Floppy";
        names[64] = "Gameboy";
        names[65] = "Gas Pump";
        names[66] = "Gavel";
        names[67] = "Goldcoin";
        names[68] = "Gumball";
        names[69] = "Hanger";
        names[70] = "Hard Drive";
        names[71] = "Hardhat";
        names[72] = "Helicopter";
        names[73] = "Hockeypuck";
        names[74] = "Hologram";
        names[75] = "House";
        names[76] = "Igloo";
        names[77] = "Index Card";
        names[78] = "Island";
        names[79] = "Joystick";
        names[80] = "Jupiter";
        names[81] = "Laptop";
        names[82] = "Lava Lamp";
        names[83] = "Led Matrix";
        names[84] = "Lightbulb";
        names[85] = "Lightning Bolt";
        names[86] = "Lipstick2";
        names[87] = "Lock";
        names[88] = "Magic 8ball";
        names[89] = "Mailbox";
        names[90] = "Maze";
        names[91] = "Megaphone";
        names[92] = "Microscope";
        names[93] = "Microwave";
        names[94] = "Mirror";
        names[95] = "Mixer";
        names[96] = "Moon";
        names[97] = "Motherboard";
        names[98] = "Mountain Snowcap";
        names[99] = "Mug";
        names[100] = "Oscilloscope";
        names[101] = "Outlet";
        names[102] = "Pager";
        names[103] = "Paintbrush";
        names[104] = "Paperclip";
        names[105] = "Parking Meter";
        names[106] = "Pencil Tip";
        names[107] = "Piano";
        names[108] = "Piggybank";
        names[109] = "Pill";
        names[110] = "Pipe";
        names[111] = "Pirateship";
        names[112] = "Plane";
        names[113] = "Polaroid";
        names[114] = "Projector";
        names[115] = "Pyramid";
        names[116] = "Qr Code";
        names[117] = "Radio Vintage";
        names[118] = "Rainbow";
        names[119] = "Rangefinder";
        names[120] = "Rgb";
        names[121] = "Ring";
        names[122] = "Road";
        names[123] = "Robot";
        names[124] = "Rock";
        names[125] = "Rocket Ship";
        names[126] = "Rotary Phone";
        names[127] = "Router";
        names[128] = "Ruler Triangular";
        names[129] = "Sailboat";
        names[130] = "Sand Castle";
        names[131] = "Satellite Dish";
        names[132] = "Satellite";
        names[133] = "Saturn";
        names[134] = "Saw";
        names[135] = "Security Monitor";
        names[136] = "Server Rack";
        names[137] = "Shower";
        names[138] = "Skateboard";
        names[139] = "Skilift";
        names[140] = "Slot Machine";
        names[141] = "Smoke Detector";
        names[142] = "Snowglobe";
        names[143] = "Snowman";
        names[144] = "Snowmobile";
        names[145] = "Space Heater";
        names[146] = "Space Station";
        names[147] = "Speaker Stack";
        names[148] = "Speedometer";
        names[149] = "Stapler";
        names[150] = "Star Sparkles";
        names[151] = "Stopwatch";
        names[152] = "Sunset";
        names[153] = "Synthesizer";
        names[154] = "Taxi";
        names[155] = "Telescope";
        names[156] = "Terminal";
        names[157] = "Thermostat";
        names[158] = "Toaster";
        names[159] = "Toiletpaper Full";
        names[160] = "Toothbrush Fresh";
        names[161] = "Tornado";
        names[162] = "Traffic Light";
        names[163] = "Transformer";
        names[164] = "Trashcan";
        names[165] = "Treasurechest";
        names[166] = "Tuba";
        names[167] = "Turing";
        names[168] = "Ufo";
        names[169] = "Usb Drive";
        names[170] = "Vacuum";
        names[171] = "Vaporwave";
        names[172] = "Vcr";
        names[173] = "Vending Machine";
        names[174] = "Vent";
        names[175] = "Vinyl";
        names[176] = "Void";
        names[177] = "Volcano";
        names[178] = "Volleyball";
        names[179] = "Walkie Talkie";
        names[180] = "Wall";
        names[181] = "Wallet";
        names[182] = "Wallsafe";
        names[183] = "Washingmachine";
        names[184] = "Watch";
        names[185] = "Wave";
        names[186] = "Webcam";
        names[187] = "Weight";
        names[188] = "Wine Barrel";
        return names;
    }

    function getBodyNames() internal pure returns (string[] memory) {
        string[] memory names = new string[](30);
        names[0] = "Bege BSOD";
        names[1] = "Bege CRT";
        names[2] = "Blue Sky";
        names[3] = "Bluegrey";
        names[4] = "Cold";
        names[5] = "Computerblue";
        names[6] = "Darkbrown";
        names[7] = "Darkpink";
        names[8] = "Foggrey";
        names[9] = "Gold";
        names[10] = "Grayscale 1";
        names[11] = "Grayscale 7";
        names[12] = "Grayscale 8";
        names[13] = "Grayscale 9";
        names[14] = "Green";
        names[15] = "Gunk";
        names[16] = "Hotbrown";
        names[17] = "Magenta";
        names[18] = "Orange Yellow";
        names[19] = "Orange";
        names[20] = "Peachy B";
        names[21] = "Peachy A";
        names[22] = "Purple";
        names[23] = "Red";
        names[24] = "Redpinkish";
        names[25] = "Rust";
        names[26] = "Slimegreen";
        names[27] = "Teal Light";
        names[28] = "Teal";
        names[29] = "Yellow";
        return names;
    }

    function getSpecsNames() internal pure returns (string[] memory) {
        string[] memory names = new string[](77);
        names[0] = "Amber";
        names[1] = "Aurora";
        names[2] = "Binary Amber";
        names[3] = "Binary Cyan";
        names[4] = "Binary Green";
        names[5] = "Blackout";
        names[6] = "Bronze";
        names[7] = "Cherry";
        names[8] = "Chromatic";
        names[9] = "Copper";
        names[10] = "Coral";
        names[11] = "Cyan";
        names[12] = "Deep Purple";
        names[13] = "Dot Cyan";
        names[14] = "Dot Red";
        names[15] = "Electric Blue";
        names[16] = "Ember";
        names[17] = "Equalizer Amber";
        names[18] = "Equalizer Cyan";
        names[19] = "Equalizer Green";
        names[20] = "Eyes Amber";
        names[21] = "Eyes Cyan";
        names[22] = "Eyes Red";
        names[23] = "Fire";
        names[24] = "Flame Orange";
        names[25] = "Gold";
        names[26] = "Half Left Amber";
        names[27] = "Half Right Cyan";
        names[28] = "Honey";
        names[29] = "Hot Pink";
        names[30] = "Ice Blue";
        names[31] = "Ice";
        names[32] = "Indigo";
        names[33] = "Lavender";
        names[34] = "Lime";
        names[35] = "Loading 30";
        names[36] = "Loading 50";
        names[37] = "Loading 70";
        names[38] = "Loading 90";
        names[39] = "Midnight";
        names[40] = "Mint";
        names[41] = "Neon Green";
        names[42] = "Noise Amber";
        names[43] = "Noise Cyan";
        names[44] = "Noise Green";
        names[45] = "Ocean";
        names[46] = "Peach";
        names[47] = "Rose";
        names[48] = "Scan Pulse Amber";
        names[49] = "Scan Pulse Cyan";
        names[50] = "Scan Pulse Green";
        names[51] = "Scan Pulse Red";
        names[52] = "Silver";
        names[53] = "Sky";
        names[54] = "Split Amber Violet";
        names[55] = "Split Cyan Amber";
        names[56] = "Split Green Red";
        names[57] = "Split Pink Cyan";
        names[58] = "Split Red Blue";
        names[59] = "Split White Teal";
        names[60] = "Steel Blue";
        names[61] = "Strobe Amber";
        names[62] = "Strobe Cyan";
        names[63] = "Strobe Green";
        names[64] = "Strobe Red";
        names[65] = "Sunrise Pink";
        names[66] = "Sunset";
        names[67] = "Tangerine";
        names[68] = "Teal";
        names[69] = "Toxic";
        names[70] = "Twilight";
        names[71] = "Violet";
        names[72] = "Warm White";
        names[73] = "Wave Amber";
        names[74] = "Wave Cyan";
        names[75] = "Wave Green";
        names[76] = "Whiteout";
        return names;
    }

    function getAntennaNames() internal pure returns (string[] memory) {
        string[] memory names = new string[](16);
        names[0] = "Arrow";
        names[1] = "Crown";
        names[2] = "Flag";
        names[3] = "Halo";
        names[4] = "Lightning Rod";
        names[5] = "None";
        names[6] = "Periscope";
        names[7] = "Propeller";
        names[8] = "Rabbit Ears";
        names[9] = "Radar";
        names[10] = "Satellite Dish";
        names[11] = "Single Rod";
        names[12] = "Sprout";
        names[13] = "Tesla Coil";
        names[14] = "Unicorn Horn";
        names[15] = "Wifi";
        return names;
    }

    function getAccessoryNames() internal pure returns (string[] memory) {
        string[] memory names = new string[](145);
        names[0] = "1n";
        names[1] = "Aardvark";
        names[2] = "Axe";
        names[3] = "Belly Chameleon";
        names[4] = "Bird Flying";
        names[5] = "Bird Side";
        names[6] = "Bling Anchor";
        names[7] = "Bling Anvil";
        names[8] = "Bling Arrow";
        names[9] = "Bling Cheese";
        names[10] = "Bling Gold Ingot";
        names[11] = "Bling Love";
        names[12] = "Bling Mask";
        names[13] = "Bling Rings";
        names[14] = "Bling Scissors";
        names[15] = "Bling Sparkles";
        names[16] = "Body Gradient Checkerdisco";
        names[17] = "Body Gradient Dawn";
        names[18] = "Body Gradient Dusk";
        names[19] = "Body Gradient Glacier";
        names[20] = "Body Gradient Ice";
        names[21] = "Body Gradient Pride";
        names[22] = "Body Gradient Redpink";
        names[23] = "Body Gradient Sunset";
        names[24] = "Broken Heart";
        names[25] = "Carrot";
        names[26] = "Chain Logo";
        names[27] = "Checker RGB";
        names[28] = "Checker Bigwalk Blue Prime";
        names[29] = "Checker Bigwalk Greylight";
        names[30] = "Checker Bigwalk Rainbow";
        names[31] = "Checker Spaced Black";
        names[32] = "Checker Spaced White";
        names[33] = "Checker Vibrant";
        names[34] = "Checkers Big Green";
        names[35] = "Checkers Big Red Cold";
        names[36] = "Checkers Black";
        names[37] = "Checkers Blue";
        names[38] = "Checkers Magenta 80";
        names[39] = "Chicken";
        names[40] = "Cloud";
        names[41] = "Clover";
        names[42] = "Collar Sunset";
        names[43] = "Cow";
        names[44] = "Decay Gray Dark";
        names[45] = "Decay Pride";
        names[46] = "Dinosaur";
        names[47] = "Dollar Bling";
        names[48] = "Dragon";
        names[49] = "Ducky";
        names[50] = "Eth";
        names[51] = "Eye";
        names[52] = "Flash";
        names[53] = "Fries";
        names[54] = "Glasses Logo Sun";
        names[55] = "Glasses Logo";
        names[56] = "Glasses";
        names[57] = "Gnars";
        names[58] = "Grease";
        names[59] = "Grid Simple Bege";
        names[60] = "Heart";
        names[61] = "Hoodiestrings Uneven";
        names[62] = "Id";
        names[63] = "Infinity";
        names[64] = "Insignia";
        names[65] = "Leaf";
        names[66] = "Lightbulb";
        names[67] = "Lines 45 Greens";
        names[68] = "Lines 45 Rose";
        names[69] = "Lobster Claw";
        names[70] = "Lp";
        names[71] = "Marsface";
        names[72] = "Matrix White";
        names[73] = "Moon Block";
        names[74] = "None";
        names[75] = "Oldshirt";
        names[76] = "Pizza Bling";
        names[77] = "Pocket Pencil";
        names[78] = "Rain";
        names[79] = "Rainbow Steps";
        names[80] = "Rgb";
        names[81] = "Robot";
        names[82] = "Safety Vest";
        names[83] = "Scarf Clown";
        names[84] = "Secret X";
        names[85] = "Shirt Black";
        names[86] = "Shrimp";
        names[87] = "Slimesplat";
        names[88] = "Small Bling";
        names[89] = "Snowflake";
        names[90] = "Stains Blood";
        names[91] = "Stains Zombie";
        names[92] = "Starburst";
        names[93] = "Stripes And Checks";
        names[94] = "Stripes Big Red";
        names[95] = "Stripes Blit";
        names[96] = "Stripes Blue Med";
        names[97] = "Stripes Brown";
        names[98] = "Stripes Olive";
        names[99] = "Stripes Red Cold";
        names[100] = "Sunset";
        names[101] = "Sweater";
        names[102] = "Tatewaku";
        names[103] = "Taxi Checkers";
        names[104] = "Tee Yo";
        names[105] = "Text Yolo";
        names[106] = "Think";
        names[107] = "Tie Black On White";
        names[108] = "Tie Dye";
        names[109] = "Tie Purple On White";
        names[110] = "Tie Red";
        names[111] = "Txt A2+b2";
        names[112] = "Txt Cc";
        names[113] = "Txt Cc2";
        names[114] = "Txt Copy";
        names[115] = "Txt Dao Black";
        names[116] = "Txt Doom";
        names[117] = "Txt Dope Text";
        names[118] = "Txt Foo Black";
        names[119] = "Txt Ico";
        names[120] = "Txt Io";
        names[121] = "Txt Lmao";
        names[122] = "Txt Lol";
        names[123] = "Txt Mint";
        names[124] = "Txt Nil Grey Dark";
        names[125] = "Txt Noun F0f";
        names[126] = "Txt Noun Green";
        names[127] = "Txt Noun Multicolor";
        names[128] = "Txt Noun";
        names[129] = "Txt Pi";
        names[130] = "Txt Pop";
        names[131] = "Txt Rofl";
        names[132] = "Txt We";
        names[133] = "Txt Yay";
        names[134] = "Uroko";
        names[135] = "Wall";
        names[136] = "Wave";
        names[137] = "Wet Money";
        names[138] = "Woolweave Bicolor";
        names[139] = "Woolweave Dirt";
        names[140] = "Yingyang";
        names[141] = "Bege";
        names[142] = "Gray Scale 1";
        names[143] = "Gray Scale 9";
        names[144] = "Ice Cold";
        return names;
    }
}
